- id: '1622659605970'
  alias: Demofunktion 01
  description: https://forum.garage-lab.de/t/smarthome-automatisierung-fuer-zuhause/8281/4
  trigger:
  - platform: state
    entity_id: binary_sensor.bewegungsmelder_occupancy
    from: 'off'
    to: 'on'
  condition: []
  action:
  - choose:
    - conditions:
      - condition: numeric_state
        entity_id: sensor.openweathermap_temperature
        above: '25'
      sequence:
      - service: light.turn_on
        target:
          entity_id: light.0x5c0272fffe51f377
        data:
          color_name: red
          brightness_pct: 100
      - delay:
          hours: 0
          minutes: 3
          seconds: 0
          milliseconds: 0
      - service: light.turn_off
        target:
          entity_id: light.0x5c0272fffe51f377
    - conditions:
      - condition: numeric_state
        entity_id: sensor.openweathermap_temperature
        above: '15'
        below: '25'
      sequence:
      - service: light.turn_on
        target:
          entity_id: light.0x5c0272fffe51f377
        data:
          color_name: yellow
          brightness_pct: 100
      - delay:
          hours: 0
          minutes: 3
          seconds: 0
          milliseconds: 0
      - service: light.turn_off
        target:
          entity_id: light.0x5c0272fffe51f377
    default:
    - service: light.turn_on
      target:
        entity_id: light.0x5c0272fffe51f377
      data:
        color_name: blue
        brightness_pct: 100
    - delay:
        hours: 0
        minutes: 3
        seconds: 0
        milliseconds: 0
    - service: light.turn_off
  mode: single
