- id: '1622605812307'
  alias: Der Bewegungsmelder schaltet die Lampe für 3 Minuten ein (Andy)
  description: 'Zwischen Sonnenuntergang und Sonnenaufgang geschieht dies nur mit
    50% Helligkeit '
  trigger:
  - platform: state
    from: 'off'
    to: 'on'
    entity_id: binary_sensor.bewegungsmelder_occupancy
  condition: []
  action:
  - choose:
    - conditions:
      - condition: sun
        before: sunrise
        after: sunset
      sequence:
      - service: light.turn_on
        data:
          color_name: blue
          brightness_pct: 50
        target:
          entity_id: light.0x5c0272fffe51f377
      - delay:
          hours: 0
          minutes: 3
          seconds: 0
          milliseconds: 0
      - service: light.turn_off
        target:
          entity_id: light.0x5c0272fffe51f377
    - conditions:
      - condition: sun
        before: sunset
        after: sunrise
      sequence:
      - service: light.turn_on
        target:
          entity_id: light.0x5c0272fffe51f377
        data:
          color_name: beige
          brightness_pct: 100
      - delay:
          hours: 0
          minutes: 3
          seconds: 0
          milliseconds: 0
      - service: light.turn_off
        target:
          entity_id: light.0x5c0272fffe51f377
        data:
          transition: 10
    default: []
  mode: single
- id: '1622655854553'
  alias: Vorlage Bewegungsmelder
  description: ''
  use_blueprint:
    path: homeassistant/motion_light.yaml
    input:
      motion_entity: binary_sensor.0xbc33acfffe207092_occupancy
      light_target:
        device_id: d3f82adc14bf0c163253e2ed6603b774
      no_motion_wait: 180
- id: '1622658968825'
  alias: Licht Temperatur
  description: ''
  trigger:
  - platform: state
    entity_id: binary_sensor.bewegungsmelder_occupancy
    from: 'off'
    to: 'on'
  condition: []
  action:
  - choose:
    - conditions:
      - condition: numeric_state
        entity_id: sensor.openweathermap_temperature
        above: '30.0'
      sequence:
      - service: light.turn_on
        target:
          entity_id: light.0x5c0272fffe51f377
        data:
          color_name: darkred
    default:
    - service: light.turn_on
      target:
        entity_id: light.0x5c0272fffe51f377
      data:
        color_name: homeassistant
  mode: single
- id: '1622659605970'
  alias: Demofunktion 01
  description: https://forum.garage-lab.de/t/smarthome-automatisierung-fuer-zuhause/8281/4
  trigger:
  - platform: state
    entity_id: binary_sensor.bewegungsmelder_occupancy
    from: 'off'
    to: 'on'
  condition: []
  action:
  - choose:
    - conditions:
      - condition: numeric_state
        entity_id: sensor.openweathermap_temperature
        above: '25'
      sequence:
      - service: light.turn_on
        target:
          entity_id: light.0x5c0272fffe51f377
        data:
          color_name: red
          brightness_pct: 100
      - delay:
          hours: 0
          minutes: 3
          seconds: 0
          milliseconds: 0
      - service: light.turn_off
        target:
          entity_id: light.0x5c0272fffe51f377
    - conditions:
      - condition: numeric_state
        entity_id: sensor.openweathermap_temperature
        above: '15'
        below: '25'
      sequence:
      - service: light.turn_on
        target:
          entity_id: light.0x5c0272fffe51f377
        data:
          color_name: yellow
          brightness_pct: 100
      - delay:
          hours: 0
          minutes: 3
          seconds: 0
          milliseconds: 0
      - service: light.turn_off
        target:
          entity_id: light.0x5c0272fffe51f377
    default:
    - service: light.turn_on
      target:
        entity_id: light.0x5c0272fffe51f377
      data:
        color_name: blue
        brightness_pct: 100
    - delay:
        hours: 0
        minutes: 3
        seconds: 0
        milliseconds: 0
    - service: light.turn_off
  mode: single
